
package GUI;

import java.awt.BorderLayout;

public class TrangChu_Form extends javax.swing.JFrame {

    private int indexTab = 0;
    TrangChu_Form thisForm;
    public TrangChu_Form() {
        initComponents();
        thisForm = this;
        setLocationRelativeTo (null);
//        btnQLNguyenLieu.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ic_logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnTuVan = new javax.swing.JButton();
        btnQLMonAn = new javax.swing.JButton();
        btnQLLuat = new javax.swing.JButton();
        btnQLNguyenLieu = new javax.swing.JButton();
        btnQLThucDon = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ic_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.png"))); // NOI18N

        btnTuVan.setBackground(new java.awt.Color(0, 51, 153));
        btnTuVan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTuVan.setForeground(new java.awt.Color(255, 255, 255));
        btnTuVan.setText("Tư vấn thực đơn");
        btnTuVan.setBorderPainted(false);
        btnTuVan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuVanActionPerformed(evt);
            }
        });

        btnQLMonAn.setBackground(new java.awt.Color(0, 51, 153));
        btnQLMonAn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQLMonAn.setForeground(new java.awt.Color(255, 255, 255));
        btnQLMonAn.setText("Quản lý món ăn");
        btnQLMonAn.setBorderPainted(false);
        btnQLMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLMonAnActionPerformed(evt);
            }
        });

        btnQLLuat.setBackground(new java.awt.Color(0, 51, 153));
        btnQLLuat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQLLuat.setForeground(new java.awt.Color(255, 255, 255));
        btnQLLuat.setText("Quản lý tập luật");
        btnQLLuat.setBorderPainted(false);
        btnQLLuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLLuatActionPerformed(evt);
            }
        });

        btnQLNguyenLieu.setBackground(new java.awt.Color(0, 51, 153));
        btnQLNguyenLieu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQLNguyenLieu.setForeground(new java.awt.Color(255, 255, 255));
        btnQLNguyenLieu.setText("Quản lý nguyên liệu");
        btnQLNguyenLieu.setBorderPainted(false);
        btnQLNguyenLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNguyenLieuActionPerformed(evt);
            }
        });

        btnQLThucDon.setBackground(new java.awt.Color(0, 51, 153));
        btnQLThucDon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQLThucDon.setForeground(new java.awt.Color(255, 255, 255));
        btnQLThucDon.setText("Quản lý thực đơn");
        btnQLThucDon.setBorderPainted(false);
        btnQLThucDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLThucDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnTuVan, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnQLMonAn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnQLLuat, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnQLNguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTuVan, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQLNguyenLieu, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQLMonAn, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQLThucDon, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQLLuat, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(149, 149, 149))
        );

        contentPanel.setPreferredSize(new java.awt.Dimension(925, 650));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/img_home.png"))); // NOI18N
        jLabel2.setText("CHƯƠNG TRÌNH TƯ VẤN THỰC ĐƠN");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(ic_logo)))
                .addGap(13, 13, 13)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ic_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTuVanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuVanActionPerformed
        // TODO add your handling code here:
        if(indexTab!=1){
            try {
                indexTab=1;
                TuVan_Form tuVan_Form = new TuVan_Form();
                contentPanel.removeAll();
                contentPanel.setLayout(new BorderLayout());
                contentPanel.add(tuVan_Form);
                contentPanel.revalidate();
                contentPanel.repaint();
            } catch (Exception e) {
                System.out.println("Lỗi");
            }
        }
    }//GEN-LAST:event_btnTuVanActionPerformed

    private void btnQLNguyenLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNguyenLieuActionPerformed
        // TODO add your handling code here:
        if(indexTab!=2){
            try {
                indexTab=2;
                QLNguyenLieu_Form tuVan_Form = new QLNguyenLieu_Form();
                contentPanel.removeAll();
                contentPanel.setLayout(new BorderLayout());
                contentPanel.add(tuVan_Form);
                contentPanel.revalidate();
                contentPanel.repaint();
            } catch (Exception e) {
                System.out.println("Lỗi");
            }
        }
    }//GEN-LAST:event_btnQLNguyenLieuActionPerformed

    private void btnQLMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLMonAnActionPerformed
        // TODO add your handling code here:
        if(indexTab!=3){
            try {
                indexTab=3;
                QLMonAn_Form tuVan_Form = new QLMonAn_Form();
                contentPanel.removeAll();
                contentPanel.setLayout(new BorderLayout());
                contentPanel.add(tuVan_Form);
                contentPanel.revalidate();
                contentPanel.repaint();
            } catch (Exception e) {
                System.out.println("Lỗi");
            }
        }
    }//GEN-LAST:event_btnQLMonAnActionPerformed

    private void btnQLThucDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLThucDonActionPerformed
        // TODO add your handling code here:
        if(indexTab!=4){
            try {
                indexTab=4;
                QLThucDon_Form tuVan_Form = new QLThucDon_Form();
                contentPanel.removeAll();
                contentPanel.setLayout(new BorderLayout());
                contentPanel.add(tuVan_Form);
                contentPanel.revalidate();
                contentPanel.repaint();
            } catch (Exception e) {
                System.out.println("Lỗi");
            }
        }
    }//GEN-LAST:event_btnQLThucDonActionPerformed

    private void btnQLLuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLLuatActionPerformed
        // TODO add your handling code here:
        if(indexTab!=5){
            try {
                indexTab=5;
                QLTapLuat_Form tuVan_Form = new QLTapLuat_Form();
                contentPanel.removeAll();
                contentPanel.setLayout(new BorderLayout());
                contentPanel.add(tuVan_Form);
                contentPanel.revalidate();
                contentPanel.repaint();
            } catch (Exception e) {
                System.out.println("Lỗi");
            }
        }
    }//GEN-LAST:event_btnQLLuatActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQLLuat;
    private javax.swing.JButton btnQLMonAn;
    private javax.swing.JButton btnQLNguyenLieu;
    private javax.swing.JButton btnQLThucDon;
    private javax.swing.JButton btnTuVan;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel ic_logo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
