
package GUI;

import ConnectData.SuKienDB;
import CustomTable.TableNguyenLieu;
import CustomTable.TableSuKien;
import Models.Luat;
import Models.SuKien;
import SuyDienTien.SuyDienTien;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class TuVan_Form extends javax.swing.JPanel {
    ArrayList<String> muaList,buoiList;
    ArrayList<SuKien> nlDaChon,allNguyenLieu;
    TableNguyenLieu 
        modelDaChon = new TableNguyenLieu(),
        modelChuaChon = new TableNguyenLieu();
    TableSuKien modelThucDon = new TableSuKien();
    
    public TuVan_Form() {
        initComponents();
        nlDaChon=new ArrayList<>();
        muaList = SuKienDB.getTenMua();
        buoiList = SuKienDB.getTenBuoi();
        cboMua.setModel(new DefaultComboBoxModel(muaList.toArray()));
        cboBuoi.setModel(new DefaultComboBoxModel(buoiList.toArray()));
        
        modelDaChon.setList(nlDaChon);
        allNguyenLieu = SuKienDB.getAllNguyenLieu();
        modelChuaChon.setList(allNguyenLieu);
        tableChuaChon.setModel(modelChuaChon);
        tableDaChon.setModel(modelDaChon);
        
    }

    public void hienthiKQ(ArrayList<SuKien> kq)
    {         
        modelThucDon.setList(kq);
        tableKQ.setModel(modelThucDon);
        tableKQ.revalidate();
        tableKQ.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboMua = new javax.swing.JComboBox<>();
        cboBuoi = new javax.swing.JComboBox<>();
        btnBoAll = new javax.swing.JButton();
        btnBo1 = new javax.swing.JButton();
        btnThem1 = new javax.swing.JButton();
        btnThemAll = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableChuaChon = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDaChon = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKQ = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnXemKQ = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(925, 650));
        setVerifyInputWhenFocusTarget(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("TƯ VẤN THỰC ĐƠN");

        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Chọn mùa");

        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Chọn buổi");

        cboMua.setForeground(new java.awt.Color(0, 51, 102));
        cboMua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboBuoi.setForeground(new java.awt.Color(0, 51, 102));
        cboBuoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBoAll.setBackground(new java.awt.Color(0, 51, 153));
        btnBoAll.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBoAll.setForeground(new java.awt.Color(255, 255, 255));
        btnBoAll.setText("<<");
        btnBoAll.setBorderPainted(false);
        btnBoAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoAllActionPerformed(evt);
            }
        });

        btnBo1.setBackground(new java.awt.Color(0, 51, 153));
        btnBo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBo1.setForeground(new java.awt.Color(255, 255, 255));
        btnBo1.setText("<");
        btnBo1.setBorderPainted(false);
        btnBo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBo1ActionPerformed(evt);
            }
        });

        btnThem1.setBackground(new java.awt.Color(0, 51, 153));
        btnThem1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThem1.setForeground(new java.awt.Color(255, 255, 255));
        btnThem1.setText(">");
        btnThem1.setBorderPainted(false);
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnThemAll.setBackground(new java.awt.Color(0, 51, 153));
        btnThemAll.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThemAll.setForeground(new java.awt.Color(255, 255, 255));
        btnThemAll.setText(">>");
        btnThemAll.setBorderPainted(false);
        btnThemAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemAllActionPerformed(evt);
            }
        });

        tableChuaChon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableChuaChon);

        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("Danh sách nguyên liệu");

        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("Danh sách nguyên liệu đã chọn");

        tableDaChon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableDaChon);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboMua, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboBuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBoAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThem1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMua, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cboBuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThemAll, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBo1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBoAll, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );

        tableKQ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableKQ);

        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Danh sách thực đơn được gợi ý");

        btnXemKQ.setBackground(new java.awt.Color(0, 51, 153));
        btnXemKQ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXemKQ.setForeground(new java.awt.Color(255, 255, 255));
        btnXemKQ.setText("Xem kết quả");
        btnXemKQ.setBorderPainted(false);
        btnXemKQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemKQActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnXemKQ, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(btnXemKQ, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemKQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemKQActionPerformed
        // TODO add your handling code here:
        ArrayList<String> input = new ArrayList<>();
        String skMua = "m"+(cboMua.getSelectedIndex()+1);
        input.add(skMua);
        String skBuoi = "b"+(cboBuoi.getSelectedIndex()+1);
        input.add(skBuoi);
        for (SuKien suKien : nlDaChon) {
            input.add(suKien.getMaSuKien().trim());
        }
        ArrayList<SuKien> ketqua = SuyDienTien.getKLSuyDienTien(input);
        hienthiKQ(ketqua);
        
    }//GEN-LAST:event_btnXemKQActionPerformed

    private void btnBoAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoAllActionPerformed
        // TODO add your handling code here:
        try {
            for (SuKien suKien : nlDaChon) {
                allNguyenLieu.add(suKien);
            }
            nlDaChon.clear();
            //Cap nhat lai du lieu vao bang
            modelDaChon.setList(nlDaChon);
            tableDaChon.setModel(modelDaChon);
            tableDaChon.revalidate();
            tableDaChon.repaint();                
            modelChuaChon.setList(allNguyenLieu);
            tableChuaChon.setModel(modelChuaChon);
            tableChuaChon.revalidate();
            tableChuaChon.repaint();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_btnBoAllActionPerformed

    private void btnBo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBo1ActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = tableDaChon.getSelectedRow();
            if(selectedRow<0 || selectedRow>=tableDaChon.getRowCount()){
                throw new Exception("Cần chọn một nguyên liệu");
            }else{
                SuKien nl = nlDaChon.get(selectedRow);
                allNguyenLieu.add(nl);
                nlDaChon.remove(nl);
                
                //Cap nhat lai du lieu vao bang
                modelDaChon.setList(nlDaChon);
                tableDaChon.setModel(modelDaChon);
                tableDaChon.revalidate();
                tableDaChon.repaint();                
                modelChuaChon.setList(allNguyenLieu);
                tableChuaChon.setModel(modelChuaChon);
                tableChuaChon.revalidate();
                tableChuaChon.repaint();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnBo1ActionPerformed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = tableChuaChon.getSelectedRow();
            if(selectedRow<0 || selectedRow>=tableChuaChon.getRowCount()){
                throw new Exception("Cần chọn một nguyên liệu");
            }else{
                SuKien nl = allNguyenLieu.get(selectedRow);
                nlDaChon.add(nl);
                allNguyenLieu.remove(nl);
                //Cap nhat lai du lieu vao bang
                modelDaChon.setList(nlDaChon);
                tableDaChon.setModel(modelDaChon);
                tableDaChon.revalidate();
                tableDaChon.repaint();
                
                modelChuaChon.setList(allNguyenLieu);
                tableChuaChon.setModel(modelChuaChon);
                tableChuaChon.revalidate();
                tableChuaChon.repaint();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnThemAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemAllActionPerformed
        // TODO add your handling code here:
        try {
            for (SuKien suKien : allNguyenLieu) {
                nlDaChon.add(suKien);
            }
            allNguyenLieu.clear();
            //Cap nhat lai du lieu vao bang
            modelDaChon.setList(nlDaChon);
            tableDaChon.setModel(modelDaChon);
            tableDaChon.revalidate();
            tableDaChon.repaint();                
            modelChuaChon.setList(allNguyenLieu);
            tableChuaChon.setModel(modelChuaChon);
            tableChuaChon.revalidate();
            tableChuaChon.repaint();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnThemAllActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBo1;
    private javax.swing.JButton btnBoAll;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnThemAll;
    private javax.swing.JButton btnXemKQ;
    private javax.swing.JComboBox<String> cboBuoi;
    private javax.swing.JComboBox<String> cboMua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableChuaChon;
    private javax.swing.JTable tableDaChon;
    private javax.swing.JTable tableKQ;
    // End of variables declaration//GEN-END:variables
}
